In [3]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

In [8]:
np.array([1, 2, 4])

array([1, 2, 4])

In [9]:
a = [1, 2, 3]
b= np.array([1, 2, 3])
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [13]:
print([1, 2, 3] + [4, 5, 6])

[1, 2, 3, 4, 5, 6]


In [14]:
print(np.array([1, 2, 3]) + np.array([4, 5, 6]))

[5 7 9]


In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a - b
print(c)
print(a)

[-3 -3 -3]
[1 2 3]


In [17]:
print(a.shape)

(3,)


In [24]:
a = np.array([
    [1],
    [2],
    [3]
])

b = np.array([
    [1],
    [2],
    [3]
])

print(a)
print(b)
print(a.shape)
print(b.shape)
c = a + b
print(a + b)
print(c.shape)


[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
(3, 1)
(3, 1)
[[2]
 [4]
 [6]]
(3, 1)


In [54]:
A = np.array([
    [1, 2],
    [2, 4],
    [3, 7]
])
print(A)
print(A.shape)
print(np.shape(A))

[[1 2]
 [2 4]
 [3 7]]
(3, 2)
(3, 2)


In [30]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a32 = A[2, 1]
print(a32)
A[2, 1] = 10
print(A)

8
[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


In [53]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(A[:, [-2]])
print(A[0:2, :])

print(A[0:2, 0:2])

A[:, [0]] = np.array([
    [6],
    [6],
    [6]
])
print(A)

[[2]
 [5]
 [8]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[[6 2 3]
 [6 5 6]
 [6 8 9]]


In [55]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

print(A + B)

[[ 2  4  6]
 [ 8 10 12]]


In [62]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

B = np.array([
    [1, 1, 1],
    [3, 3, 3]
])

print(A.shape)
print(B.shape)

print(A + B)

(2, 3)
(2, 3)
[[2 3 4]
 [7 8 9]]


In [64]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

print(A + 1)
print(A * 2)

[[2 3 4]
 [5 6 7]]
[[ 2  4  6]
 [ 8 10 12]]


In [68]:
a = np.array([
    [1],
    [2],
    [3]
])

b = np.array([
    [2],
    [3],
    [4]
])

print(a.shape)
print(b.shape)

print(a * b)
print(a @ b)

(3, 1)
(3, 1)
[[ 2]
 [ 6]
 [12]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [70]:
a = np.array([1, 2, 3])

b = np.array([2, 3, 4])
print(a.shape)
print(b.shape)
print(a @ b)

(3,)
(3,)
20


In [74]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

B = np.array([
    [1, 2, 3]
])
print(A.shape)
print(B.shape)
print(A * B)

(2, 3)
(1, 3)
[[ 1  4  9]
 [ 4 10 18]]


In [79]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [4, 5, 6]
])

print(A.shape)
print(B.shape)
print(A @ B)
print(np.matmul(A, B))
print(np.dot(A, B))

(2, 3)
(3, 3)
[[21 27 33]
 [48 63 78]]
[[21 27 33]
 [48 63 78]]
[[21 27 33]
 [48 63 78]]


In [90]:
a = np.array([
    [1],
    [1],
    [1]
])
print(a)
print(np.cumsum(a))

[[1]
 [1]
 [1]]
[1 2 3]


In [102]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [4, 5, 6]
])
print(np.sum(A))
print(np.sum(A, axis=1, keepdims=True))
print(np.sum(A, axis=1, keepdims=True).shape)

36
[[ 6]
 [15]
 [15]]
(3, 1)


In [108]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [4, 5, 6]
])

A_mean = np.mean(A, axis=0, keepdims=True)

print(A)
print(A_mean)
print(A - A_mean)

[[1 2 3]
 [4 5 6]
 [4 5 6]]
[2. 5. 5.]
[[-1. -3. -2.]
 [ 2.  0.  1.]
 [ 2.  0.  1.]]


In [112]:
a = np.array([5])
print(a)
print(a.shape)

[5]
(1,)


In [113]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [115]:
print(np.zeros((3, 2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [116]:
print(np.ones((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [117]:
np.diag([4, 5, 6, 7])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

In [119]:
v1 = np.array([
    [1],
    [2],
    [3]
])

v2 = np.array([
    [1],
    [2],
    [3]
])

print(v1.T @ v2)
print(v1 @ v2.T)

[[14]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [120]:
print(np.matmul(v1.T, v2))
print(np.dot(v1.T, v2))
print(v1.T @ v2)

[[14]]
[[14]]
[[14]]
