In [1]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

In [2]:
a = [1, 2, 3]
b= np.array([1, 2, 3])
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
d = a - b
print(c)
print(a)

[5 7 9]
[1 2 3]


In [12]:
print(np.shape(a))

(3,)


In [7]:
a = np.array([ [1,2]
              ,[2,2], 
               [3,2]])
print(a.shape)

(3, 2)


In [8]:
a = np.array([ [1]
              ,[2], 
               [3]])
print(a.shape)

(3, 1)


In [13]:
a = np.array([
    [1],
    [2],
    [3]
])

b = np.array([
    [1],
    [2],
    [3]
])

print(a)
print(b)
print(a.shape)
print(b.shape)
c = a + b
print(a + b)
print(c.shape)


[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
(3, 1)
(3, 1)
[[2]
 [4]
 [6]]
(3, 1)


In [14]:
a*b

array([[1],
       [4],
       [9]])

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a*b

array([ 4, 10, 18])

In [16]:
#Vector Dot/Inner Product
a.dot(b)

32

In [17]:
A = np.array([
    [1, 2],
    [2, 4],
    [3, 7]
])
print(A)
print(A.shape)
print(np.shape(A))

[[1 2]
 [2 4]
 [3 7]]
(3, 2)
(3, 2)


In [18]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a32 = A[2, 1]
print(a32)
A[2, 1] = 10
print(A)

8
[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


In [19]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

print(A + B)

[[ 2  4  6]
 [ 8 10 12]]


In [20]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

B = np.array([
    [1, 1, 1],
    [3, 3, 3]
])

print(A.shape)
print(B.shape)


(2, 3)
(2, 3)


In [21]:
a = np.array([
    [1],
    [2],
    [3]
])

b = np.array([
    [2],
    [3],
    [4]
])

print(a.shape)
print(b.shape)

print(a * b)
print(a @ b)

(3, 1)
(3, 1)
[[ 2]
 [ 6]
 [12]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [23]:
print(a @ b.T)

[[ 2  3  4]
 [ 4  6  8]
 [ 6  9 12]]


In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])


In [25]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [4, 5, 6]
])

print(A.shape)
print(B.shape)
print(A @ B)
print(np.matmul(A, B))
print(np.dot(A, B))

(2, 3)
(3, 3)
[[21 27 33]
 [48 63 78]]
[[21 27 33]
 [48 63 78]]
[[21 27 33]
 [48 63 78]]


In [27]:
A*B

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 